name: "my_new_project"
version: "1.0.0"
config-version: 2

profile: "default"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_new_project:
    staging:
      sql_server_dbo:
        +materialized: view
        stg_sql_server_dbo_addresses:
          +materialized: view
        stg_sql_server_dbo_users:
          +materialized: view
        stg_sql_server_dbo_events:
          +materialized: view

seeds:
  +database: "ALUMNO30_DEV_BRONZE_DB"
  +schema: "SEEDS"
